# SQLite. Versions 3.8.0 and up are supported.
#   gem install pg
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'
#
development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: shopify_production
  pool: 5
  timeout: 5000